config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get 'about' => 'about#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  
  include HttpAuthConcern

  def show
    @products_count = Product.count
    @categories_count = Category.count
    @products_per_category = Category.order(name: :asc).select(:id, :name).distinct.map do |category|
      {id: category[:id], name: category[:name], count: category.products.count}
    end
  end
end

app/views/admin/dashboard/show.html.erb
<header class="page-header">
  <h1>Dashboard</h1>
</header>

<div class="panel panel-default">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 50%">Database Entry</th>
        <th style="width: 50%">Count</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to 'Categories', admin_categories_path %></td>
        <td><%= @categories_count %></td>
      </tr>
      <tr>
        <td><%= link_to 'Products', admin_products_path %></td>
        <td><%= @products_count %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="panel panel-default">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 50%">Category</th>
        <th style="width: 50%">Count</th>
      </tr>
    </thead>
    <tbody>
      <% @products_per_category.each do |category| %>
        <tr>
          <td><%= link_to "#{category[:name]}", "categories/#{category[:id]}" %></td>
          <td><%= category[:count] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>